MetioTube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('MetioTube.main_app.urls')),
                  path('auth/', include('MetioTube.metio_tube_auth.urls')),
                  path('profile/', include('MetioTube.profiles.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MetioTube/main_app/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from MetioTube.core.validators import validate_video_file, validate_image

UserModel = get_user_model()


class Video(models.Model):
    title = models.CharField(
        max_length=30
    )

    description = models.TextField()

    thumbnail = CloudinaryField(
        resource_type='image',
        blank=True,
        validators=(validate_image,),
    )

    video_file = CloudinaryField(
        resource_type='video',
        validators=(validate_video_file,),
    )

    date = models.DateTimeField(
        auto_now_add=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title


class LikeDislike(models.Model):
    # 0 for dislike 1 for like
    like_or_dislike = models.IntegerField(
        help_text='1 for like 0 for dislike'
    )

    video = models.ForeignKey(
        Video,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )


class VideoView(models.Model):
    video = models.ForeignKey(
        Video,
        on_delete=models.CASCADE,
    )

    session_key = models.CharField(
        max_length=32,
        blank=True
    )


class CommentVideo(models.Model):
    video = models.ForeignKey(
        Video,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    date = models.DateTimeField(
        auto_now_add=True,
    )

    content = models.TextField()

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block title %}MetioTube{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'images/roko.ico' %}" rel="icon">
    <script src="{% static 'js/metin.js' %}"></script>

    {% block custom_style_head %}
    {% endblock %}

    {% block custom_script_head %}
    {% endblock %}

</head>
<body>

{% include 'base/header.html' %}

{% block content %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

{% block custom_script_body %}
{% endblock %}

</body>
</html>

templates/base/header.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home page' %}" onmouseover="roko()" onmouseleave="bezroko()">
            <img src="{% static 'images/roko.ico' %}" width="30" height="40" id="metio">
            MetioTube
        </a>

        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarsExample03" style="">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'upload video' %}">Upload Video</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'subscribers page' %}">Subscriptions</a>
                </li>

                <form class="d-flex nav-item" method="get" action="{% url 'search video' %}">
                    <input name="q" class="form-control me-2" type="search" placeholder="Search" required>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>

            </ul>

            <ul class="navbar-nav d-flex">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile page' request.user.id %}">Profile</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user logout' %}">Log Out</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user login' %}">Log In</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>

templates/base/show-videos.html
{% load static %}
{% load split_get_first_filter %}
<div class="container">
    {% if videos %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for video in videos %}
                <div class="col">
                    <div class="card text-white bg-secondary m-4 card-hover">
                        <div class="card-top-container">
                            <a href="{% url 'video page' video.id %}">
                                {% if video.thumbnail %}
                                    <img class="card-img-top" src="{{ video.thumbnail.url }}">
                                {% else %}
                                    <img class="card-img-top" src="{% static 'images/default_thumbnail.jpg' %}">
                                {% endif %}
                                <img class="play-icon" src="{% static 'images/play-button.png' %}">
                            </a>
                        </div>

                        <div class="card-body">
                            <h5 class="card-title text-center">{{ video.title }}</h5>
                            <div class="d-flex justify-content-between">
                                <span class="text-muted">{{ video.videoview_set.count }} views</span>
                                <span class="text-muted">{{ video.date|timesince|split_get_first:',' }} ago</span>
                            </div>
                        </div>

                        {% if not profile_page %}
                            <div class="card-footer">
                                <h6>
                                    <a class="text-muted text-decoration-none"
                                       href="{% url 'profile page' video.user_id %}">
                                        {% if video.user.profile.profile_picture %}
                                            <img class="img-profile-small"
                                                 src="{{ video.user.profile.profile_picture.url }}">
                                        {% else %}
                                            <img class="img-profile-small"
                                                 src="{% static 'images/default_profile.jpg' %}">
                                        {% endif %}
                                        {{ video.user.profile.username }}
                                    </a>
                                </h6>
                            </div>
                        {% endif %}
                    </div>

                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="text-center text-white">
            There is no videos!
        </h1>
    {% endif %}

    {% if is_paginated %}
        <div class="d-flex justify-content-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?{% if query %}q={{ query }}&{% endif %}page={{ page_obj.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?{% if query %}q={{ query }}&{% endif %}page={{ page_obj.next_page_number }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}

</div>